/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package talktime.view;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JPanel;
import static talktime.TalkTime.mainFrame;
import talktime.standards.CombinePanel;
import talktime.standards.SessionManager;
import talktime.view.user.AboutPanel;
import talktime.view.user.CartPanel;
import talktime.view.user.CategoryPanel;
import talktime.view.user.CategoryPanel1;
import talktime.view.user.CommentListPanel;
import talktime.view.user.ContactPanel;
import talktime.view.user.PostCommentPanel;
import talktime.view.user.ProfilePanel;
import talktime.view.user.SettingPanel;
import talktime.view.user.PostPanel;
import talktime.view.user.SearchPanel;
import talktime.view.user.ThreadListPanel;
import talktime.view.user.TrendingPanel;

/**
 *
 * @author Gopal
 */
public class HomePanel extends javax.swing.JPanel {

    /**
     * Creates new form HomePanel
     */
    public HomePanel() {
        initComponents();
        
        new CombinePanel(SubHomePanel,new CategoryPanel()); 
        //new CombinePanel(SubHomePanel,new subUserPanel());  
       //jLabel1.setText(SessionManager.getEmail());      
    }
    public HomePanel(int catId){
      initComponents();
      new CombinePanel(SubHomePanel,new PostPanel(catId));
      
    }
    public HomePanel(String message,String id){
      initComponents();
      new CombinePanel(SubHomePanel,new ThreadListPanel(message,id));
      
    }
    public HomePanel(int tId,String message){
     initComponents();
     new CombinePanel(SubHomePanel,new PostCommentPanel(tId,message));
    }
    public HomePanel(String message,String tId,Boolean v){
     initComponents();
     new CombinePanel(SubHomePanel,new CommentListPanel(message,tId));
    }
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        searchTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        trendingButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        contactusButton = new javax.swing.JButton();
        aboutusButton = new javax.swing.JButton();
        SubHomePanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1100, 650));

        HeaderPanel.setBackground(new java.awt.Color(0, 51, 102));
        HeaderPanel.setPreferredSize(new java.awt.Dimension(1100, 77));

        logoutButton.setBackground(new java.awt.Color(255, 51, 0));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("logout");
        logoutButton.setToolTipText("");
        logoutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 51, 0));
        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(255, 255, 255));
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchTF.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchTF.setForeground(new java.awt.Color(153, 153, 153));
        searchTF.setText("  Search something...");
        searchTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchTF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchTFMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo4.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TalkTime");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutButton)
                .addGap(37, 37, 37))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPanel.setBackground(new java.awt.Color(24, 119, 242));
        MenuPanel.setMaximumSize(new java.awt.Dimension(200, 573));
        MenuPanel.setMinimumSize(new java.awt.Dimension(200, 573));
        MenuPanel.setPreferredSize(new java.awt.Dimension(200, 573));

        homeButton.setBackground(new java.awt.Color(24, 119, 242));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        trendingButton.setBackground(new java.awt.Color(24, 119, 242));
        trendingButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        trendingButton.setForeground(new java.awt.Color(255, 255, 255));
        trendingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/trending.png"))); // NOI18N
        trendingButton.setText("Trending");
        trendingButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trendingButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                trendingButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                trendingButtonMouseExited(evt);
            }
        });
        trendingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trendingButtonActionPerformed(evt);
            }
        });

        profileButton.setBackground(new java.awt.Color(24, 119, 242));
        profileButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        profileButton.setForeground(new java.awt.Color(255, 255, 255));
        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        profileButton.setText("Profile");
        profileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileButtonMouseExited(evt);
            }
        });
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });

        settingsButton.setBackground(new java.awt.Color(24, 119, 242));
        settingsButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        settingsButton.setForeground(new java.awt.Color(255, 255, 255));
        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/setting.png"))); // NOI18N
        settingsButton.setText("Settings");
        settingsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsButtonMouseExited(evt);
            }
        });
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        contactusButton.setBackground(new java.awt.Color(24, 119, 242));
        contactusButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        contactusButton.setForeground(new java.awt.Color(255, 255, 255));
        contactusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact1.png"))); // NOI18N
        contactusButton.setText("Contact Us");
        contactusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactusButtonMouseExited(evt);
            }
        });
        contactusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactusButtonActionPerformed(evt);
            }
        });

        aboutusButton.setBackground(new java.awt.Color(24, 119, 242));
        aboutusButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        aboutusButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutusButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about.png"))); // NOI18N
        aboutusButton.setText("About Us");
        aboutusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutusButtonMouseExited(evt);
            }
        });
        aboutusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
            .addComponent(trendingButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
            .addComponent(profileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
            .addComponent(settingsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
            .addComponent(contactusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
            .addComponent(aboutusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trendingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(profileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        SubHomePanel.setBackground(new java.awt.Color(255, 255, 255));
        SubHomePanel.setLayout(new javax.swing.BoxLayout(SubHomePanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SubHomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubHomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
      try {
      SessionManager.setLoggedIn(false);
      SessionManager.setSno(0);
      SessionManager.setEmail("");
      LoginPanel loginPanel = new LoginPanel();
      mainFrame.setContentPane(loginPanel);
      mainFrame.pack();
      mainFrame.setVisible(true);
     // new CombinePanel(SubHomePanel,new LoginPanel());
      }
      catch(SQLException e)
      {
        e.printStackTrace();
      } 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void searchTFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchTFMouseClicked
       searchTF.setText("");
       searchTF.setForeground(Color.black);
               // TODO add your handling code here:
    }//GEN-LAST:event_searchTFMouseClicked

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
      homeButton.setBackground(new Color(255,51,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
     homeButton.setBackground(new Color(24,119,242));
// TODO add your handling code here:
    }//GEN-LAST:event_homeButtonMouseExited

    private void trendingButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trendingButtonMouseEntered
       trendingButton.setBackground(new Color(255,51,0));
        // TODO add your handling code here:
    }//GEN-LAST:event_trendingButtonMouseEntered

    private void trendingButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trendingButtonMouseExited
       trendingButton.setBackground(new Color(24,119,242)); // TODO add your handling code here:
    }//GEN-LAST:event_trendingButtonMouseExited

    private void profileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseEntered
       profileButton.setBackground(new Color(255,51,0)); // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonMouseEntered

    private void profileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseExited
       profileButton.setBackground(new Color(24,119,242)); // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonMouseExited

    private void settingsButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseEntered
        settingsButton.setBackground(new Color(255,51,0));// TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonMouseEntered

    private void settingsButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseExited
       settingsButton.setBackground(new Color(24,119,242)); // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonMouseExited

    private void contactusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactusButtonMouseEntered
        contactusButton.setBackground(new Color(255,51,0));// TODO add your handling code here:
    }//GEN-LAST:event_contactusButtonMouseEntered

    private void contactusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactusButtonMouseExited
        contactusButton.setBackground(new Color(24,119,242));// TODO add your handling code here:
    }//GEN-LAST:event_contactusButtonMouseExited

    private void aboutusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusButtonMouseEntered
        aboutusButton.setBackground(new Color(255,51,0));// TODO add your handling code here:
    }//GEN-LAST:event_aboutusButtonMouseEntered

    private void aboutusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusButtonMouseExited
        aboutusButton.setBackground(new Color(24,119,242));// TODO add your handling code here:
    }//GEN-LAST:event_aboutusButtonMouseExited

    private void aboutusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutusButtonActionPerformed
      new CombinePanel(SubHomePanel,new AboutPanel()); 
        // TODO add your handling code here:
    }//GEN-LAST:event_aboutusButtonActionPerformed

    private void contactusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactusButtonActionPerformed
      new CombinePanel(SubHomePanel,new ContactPanel());
        // TODO add your handling code here:
    }//GEN-LAST:event_contactusButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
      new CombinePanel(SubHomePanel,new SettingPanel());
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
      new CombinePanel(SubHomePanel,new ProfilePanel()); 
        // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
         new CombinePanel(SubHomePanel,new CategoryPanel()); 
       // TODO add your handling code here:
    }//GEN-LAST:event_homeButtonActionPerformed

    private void trendingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trendingButtonActionPerformed
        new CombinePanel(SubHomePanel,new TrendingPanel());
        // TODO add your handling code here:
    }//GEN-LAST:event_trendingButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
       String q= searchTF.getText();
        new CombinePanel(SubHomePanel,new SearchPanel(q)); 
// TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel SubHomePanel;
    private javax.swing.JButton aboutusButton;
    private javax.swing.JButton contactusButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTF;
    private javax.swing.JButton settingsButton;
    private javax.swing.JButton trendingButton;
    // End of variables declaration//GEN-END:variables
}
