/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package talktime.view;

import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import static talktime.TalkTime.mainFrame;
import talktime.standards.DatabaseHandler;
import talktime.standards.SessionManager;
/**
 *
 * @author Gopal
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public DatabaseHandler db = new DatabaseHandler();
    
    
    public LoginPanel() throws SQLException {
        initComponents();
    }
    
    private void loginButton(ActionEvent e)
    {
        String email = username.getText();
        String pass = String.valueOf(password.getPassword());
        if (!email.isEmpty() && !pass.isEmpty()) {
            try {
                // Check if email and password match
                String sql ="SELECT * FROM users WHERE user_email = ?";
                String[] values = {email};
                ResultSet rs = db.executePrepare(sql,values);
                //rs.next();
               // System.out.println(rs.getString("user_email"));
                if (rs.next() && rs.getString("user_pass").equals(pass)) {
                    // Successful login
                    int sno = rs.getInt("sno");
                    
                    // Store user data in session
                    SessionManager.setLoggedIn(true);
                    SessionManager.setSno(sno);
                    SessionManager.setEmail(email);
                    HomePanel homePanel = new HomePanel();
                    mainFrame.setContentPane(homePanel);
                    mainFrame.pack();
                    mainFrame.setVisible(true);
                    //DailogBox dailog = new DailogBox(mainFrame,true,"Succesfull login.");
                } else {
                    // Failed login
                    DailogBox dailog = new DailogBox(mainFrame,true,"Invalid username or password.");
                }
            }catch (SQLException ex) {
                ex.printStackTrace();
              DailogBox dailog = new DailogBox(mainFrame,true,"An error occurred. Please try again.");
            }
        } else {
               DailogBox dailog= new DailogBox(mainFrame,true,"Fill out all the fields properly.");     
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subLoginPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        forgotPassword = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();
        newHereLabel = new javax.swing.JLabel();
        createAccount = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 119, 242));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setName("loginPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 650));

        subLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        subLoginPanel.setPreferredSize(new java.awt.Dimension(550, 650));

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(24, 119, 242));
        welcomeLabel.setText("WELCOME!");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        passwordLabel.setText("Password\n");

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        forgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forgotPassword.setForeground(new java.awt.Color(24, 119, 242));
        forgotPassword.setText("Forgot your password?");
        forgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        loginButton.setBackground(new java.awt.Color(255, 51, 0));
        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        newHereLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newHereLabel.setText("New here?");

        createAccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        createAccount.setForeground(new java.awt.Color(24, 119, 242));
        createAccount.setText("Create an Account");
        createAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout subLoginPanelLayout = new javax.swing.GroupLayout(subLoginPanel);
        subLoginPanel.setLayout(subLoginPanelLayout);
        subLoginPanelLayout.setHorizontalGroup(
            subLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subLoginPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addGroup(subLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(password)
                    .addComponent(username)
                    .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(subLoginPanelLayout.createSequentialGroup()
                        .addGroup(subLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(subLoginPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(newHereLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(createAccount))
                            .addComponent(forgotPassword))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        subLoginPanelLayout.setVerticalGroup(
            subLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subLoginPanelLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(welcomeLabel)
                .addGap(36, 36, 36)
                .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgotPassword)
                .addGap(28, 28, 28)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(subLoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newHereLabel)
                    .addComponent(createAccount))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo3.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(subLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(subLoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(logo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccountMouseClicked
      RegisterationPanel registerationPanel = new RegisterationPanel();
      mainFrame.setContentPane(registerationPanel);
      mainFrame.pack();
      mainFrame.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_createAccountMouseClicked

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
       loginButton(evt);    
 
// TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createAccount;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JButton loginButton;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel newHereLabel;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPanel subLoginPanel;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
