/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package talktime.view;

import java.awt.event.ActionEvent;
import java.sql.SQLException;
import static talktime.TalkTime.mainFrame;
import talktime.standards.DatabaseHandler;

/**
 *
 * @author Gopal
 */
public class RegisterationPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterationPanel
     */
    
    
    public RegisterationPanel() {
        initComponents();
    }
         
            
            
            
    private void registerButton(ActionEvent evt){
       String name = username.getText();
       String email = emailTF.getText();
       String pass = String.valueOf( password.getPassword());
       String confirm = String.valueOf( confirmPassword.getPassword());
       String contact = contactTF.getText();
       if(!name.isEmpty() && !email.isEmpty() && !pass.isEmpty() && !confirm.isEmpty() && !contact.isEmpty() ){
            if(pass.equals(confirm)){
                try{
                   DatabaseHandler db = new DatabaseHandler(); 
                   String sql = "insert into users(user_email,user_pass) values(?,?)";
                   String[] values = {name,pass};
                   db.executeInsertPrepare(sql, values);
                   String sql1 = "insert into profiles(user_name,name,email,contact) values(?,?,?,?)";
                   String[] values1 = {name," ",email,contact};
                   db.executeInsertPrepare(sql1, values1);
                   DailogBox dailog = new DailogBox(mainFrame,true,"Registration succesfull please login."); 
                }catch(SQLException ex){
                    ex.printStackTrace();
                    DailogBox dailog = new DailogBox(mainFrame,true,"An error occurred. Please try again.");  
                }
            }
            else{
                DailogBox dailog= new DailogBox(mainFrame,true,"Password not matched.");      
            }
       }else {
          DailogBox dailog= new DailogBox(mainFrame,true,"Fill out all the fields properly.");      
       }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subRegisterationPanel = new javax.swing.JPanel();
        createAccountLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmPassword = new javax.swing.JPasswordField();
        confirmLabel = new javax.swing.JLabel();
        contactTF = new javax.swing.JTextField();
        contactLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();
        alreadyLabel = new javax.swing.JLabel();
        loginLabel = new javax.swing.JLabel();
        logoLabel = new javax.swing.JLabel();
        logoName1Label = new javax.swing.JLabel();
        logoName2Label = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();
        info2Label = new javax.swing.JLabel();
        info3Label = new javax.swing.JLabel();

        setBackground(new java.awt.Color(24, 119, 242));
        setMaximumSize(new java.awt.Dimension(1100, 650));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setPreferredSize(new java.awt.Dimension(1100, 650));

        subRegisterationPanel.setBackground(new java.awt.Color(255, 255, 255));
        subRegisterationPanel.setPreferredSize(new java.awt.Dimension(718, 650));

        createAccountLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        createAccountLabel.setForeground(new java.awt.Color(24, 119, 242));
        createAccountLabel.setText("Create an Account");

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/username.png"))); // NOI18N
        usernameLabel.setText("Username");

        username.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        passwordLabel.setText("Password");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/email.png"))); // NOI18N
        emailLabel.setText("Email");

        emailTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        confirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        confirmLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirm.png"))); // NOI18N
        confirmLabel.setText("Confirm Password");

        contactTF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        contactLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        contactLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/contact.png"))); // NOI18N
        contactLabel.setText("Contact");

        registerButton.setBackground(new java.awt.Color(255, 51, 0));
        registerButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        alreadyLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        alreadyLabel.setText("Already have an account?");

        loginLabel.setBackground(new java.awt.Color(24, 119, 242));
        loginLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(24, 119, 242));
        loginLabel.setText("Login");
        loginLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout subRegisterationPanelLayout = new javax.swing.GroupLayout(subRegisterationPanel);
        subRegisterationPanel.setLayout(subRegisterationPanelLayout);
        subRegisterationPanelLayout.setHorizontalGroup(
            subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subRegisterationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createAccountLabel)
                .addGap(118, 118, 118))
            .addGroup(subRegisterationPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subRegisterationPanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(alreadyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loginLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(subRegisterationPanelLayout.createSequentialGroup()
                        .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(subRegisterationPanelLayout.createSequentialGroup()
                                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(confirmLabel)
                                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(64, 64, 64))))
        );
        subRegisterationPanelLayout.setVerticalGroup(
            subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subRegisterationPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(createAccountLabel)
                .addGap(26, 26, 26)
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subRegisterationPanelLayout.createSequentialGroup()
                        .addComponent(confirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subRegisterationPanelLayout.createSequentialGroup()
                        .addComponent(confirmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subRegisterationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alreadyLabel)
                    .addComponent(loginLabel))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        logoLabel.setBackground(new java.awt.Color(255, 255, 255));
        logoLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo4.png"))); // NOI18N

        logoName1Label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        logoName1Label.setForeground(new java.awt.Color(255, 51, 0));
        logoName1Label.setText("Talk");

        logoName2Label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        logoName2Label.setText("Time");

        infoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        infoLabel.setForeground(new java.awt.Color(255, 255, 255));
        infoLabel.setText("A few clicks away ");

        info2Label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        info2Label.setForeground(new java.awt.Color(255, 255, 255));
        info2Label.setText("from creating your ");

        info3Label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        info3Label.setForeground(new java.awt.Color(255, 255, 255));
        info3Label.setText("account...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoName1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logoName2Label))
                    .addComponent(info2Label)
                    .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(subRegisterationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(subRegisterationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(logoName1Label)
                        .addComponent(logoName2Label)))
                .addGap(28, 28, 28)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(info3Label)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
      try{
      LoginPanel loginPanel = new LoginPanel();
      mainFrame.setContentPane(loginPanel);
      mainFrame.pack();
      mainFrame.setVisible(true); 
      }
      catch(SQLException e)
      {
        e.printStackTrace(); 
      }
      
   
    // TODO add your handling code here:
    }//GEN-LAST:event_loginLabelMouseClicked

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
       registerButton(evt); // TODO add your handling code here:
    }//GEN-LAST:event_registerButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alreadyLabel;
    private javax.swing.JLabel confirmLabel;
    private javax.swing.JPasswordField confirmPassword;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JTextField contactTF;
    private javax.swing.JLabel createAccountLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel info2Label;
    private javax.swing.JLabel info3Label;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JLabel logoName1Label;
    private javax.swing.JLabel logoName2Label;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JPanel subRegisterationPanel;
    private javax.swing.JTextField username;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
